import type { AuditResult } from "./audit";
import type { ModelAnalysis } from "./model";
import { paperStudies } from "./study";

export function buildReceipt(audit: AuditResult, analysis: ModelAnalysis) {
  const findings = analysis.issues
    .map((issue) => `- **${issue.title} (${issue.severity})** — ${issue.evidence}\n  - Paper anchor: ${issue.paperAnchor}\n  - Correction: ${issue.correction}`)
    .join("\n");
  const papers = paperStudies.map((paper) => `- [${paper.title}](${paper.sourceUrl}) — ${paper.authors}, ${paper.year}`).join("\n");

  return `# Second Lab Paper Review Receipt

## Sources

${papers}

## Review

- **Claim reviewed:** ${analysis.extractedClaim}
- **Source:** ${analysis.metricSource}
- **Evidence status:** ${audit.receiptStatus}
- **Package fingerprint:** \`${audit.datasetFingerprint}\`
- **Papers reviewed:** ${audit.paperCount}

## Findings

${findings || "No discrepancies were returned by the reviewer."}

## Correction

**${analysis.correctionTitle}.** ${analysis.correctionRationale}

## Interpretation boundary

This receipt reports text-grounded implementation discrepancies for review. It is not a truth certificate, peer review, or allegation of misconduct. GPT-5.6 selects and explains evidence; the source package remains available for human inspection.

---

Generated by Second Lab on ${audit.generatedAt}.
`;
}
